apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: your-app-label
  ports:
    - protocol: TCP
      port: 80       # External port exposed by the LoadBalancer
      targetPort: 8080 # Internal port of your container
